if (userAgent.isNode) {
  var _fs   = require('fs'),
      _path = require('path');

  // Find all Swagger files, and add them to the path.realWorld array
  path.realWorld = [];
  findSwaggerFiles(__dirname);
  // console.log(JSON.stringify(path.realWorld, null, 4));

  function findSwaggerFiles(dir) {
    _fs.readdirSync(dir).forEach(function(name) {
      var fullName = _path.join(dir, name);
      var ext = _path.extname(name);
      var stat = _fs.statSync(fullName);

      if (stat.isFile() &&
        name !== 'patch.json' &&
        name !== 'fixup.json' &&
        ['.json', '.yaml', '.yml'].indexOf(ext) >= 0) {
        // This is a Swagger file, so add it
        path.realWorld.push('specs/real-world/' + _path.relative(__dirname, fullName));
      }
      else if (stat.isDirectory()) {
        // Recursively process this sub-directory
        findSwaggerFiles(fullName);
      }
    });
  }
}
else {
  // In browsers, just use this hard-coded list of files
  path.realWorld = [
    'specs/real-world/18f.us/0.1/swagger.json',
    'specs/real-world/backupify.com/1.0.0/swagger.json',
    'specs/real-world/bikewise.org/v2/swagger.json',
    'specs/real-world/bitdango.com/1.0.0/swagger.json',
    'specs/real-world/blackberry.com/1.0.0/swagger.json',
    'specs/real-world/cambase.io/1.0/swagger.json',
    'specs/real-world/citycontext.com/1.0.0/swagger.json',
    'specs/real-world/clarify.io/1.0.8/swagger.json',
    'specs/real-world/clickmeter.com/v2/swagger.json',
    'specs/real-world/core.ac.uk/2.0/swagger.json',
    'specs/real-world/cybertaxonomy.eu/1.0/swagger.json',
    'specs/real-world/daisycon.com/1.0.0/swagger.json',
    'specs/real-world/datumbox.com/1.0/swagger.json',
    'specs/real-world/eriomem.net/0.1/swagger.json',
    'specs/real-world/exavault.com/1.0.0/swagger.json',
    'specs/real-world/firebrowse.org/1.1.15 beta (2015-08-24 18:25:33 )/swagger.json',
    'specs/real-world/geneea.com/1.0/swagger.json',
    'specs/real-world/geodesystems.com/1.0.0/swagger.json',
    'specs/real-world/gettyimages.com/3.0/swagger.json',
    'specs/real-world/glugbot.com/1/swagger.json',
    'specs/real-world/googleapis.com/adexchangebuyer/v1.2/swagger.json',
    'specs/real-world/googleapis.com/adexchangebuyer/v1.3/swagger.json',
    'specs/real-world/googleapis.com/adexchangebuyer/v1.4/swagger.json',
    'specs/real-world/googleapis.com/adexchangeseller/v1/swagger.json',
    'specs/real-world/googleapis.com/adexchangeseller/v1.1/swagger.json',
    'specs/real-world/googleapis.com/adexchangeseller/v2.0/swagger.json',
    'specs/real-world/googleapis.com/admin/datatransfer_v1/swagger.json',
    'specs/real-world/googleapis.com/admin/email_migration_v2/swagger.json',
    'specs/real-world/googleapis.com/admin/reports_v1/swagger.json',
    'specs/real-world/googleapis.com/adsense/v1.2/swagger.json',
    'specs/real-world/googleapis.com/adsense/v1.3/swagger.json',
    'specs/real-world/googleapis.com/adsense/v1.4/swagger.json',
    'specs/real-world/googleapis.com/adsensehost/v4.1/swagger.json',
    'specs/real-world/googleapis.com/analytics/v2.4/swagger.json',
    'specs/real-world/googleapis.com/analytics/v3/swagger.json',
    'specs/real-world/googleapis.com/androidenterprise/v1/swagger.json',
    'specs/real-world/googleapis.com/androidpublisher/v1/swagger.json',
    'specs/real-world/googleapis.com/androidpublisher/v1.1/swagger.json',
    'specs/real-world/googleapis.com/androidpublisher/v2/swagger.json',
    'specs/real-world/googleapis.com/appsactivity/v1/swagger.json',
    'specs/real-world/googleapis.com/appstate/v1/swagger.json',
    'specs/real-world/googleapis.com/autoscaler/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/bigquery/v2/swagger.json',
    'specs/real-world/googleapis.com/blogger/v2/swagger.json',
    'specs/real-world/googleapis.com/blogger/v3/swagger.json',
    'specs/real-world/googleapis.com/books/v1/swagger.json',
    'specs/real-world/googleapis.com/calendar/v3/swagger.json',
    'specs/real-world/googleapis.com/civicinfo/v2/swagger.json',
    'specs/real-world/googleapis.com/classroom/v1/swagger.json',
    'specs/real-world/googleapis.com/clouddebugger/v2/swagger.json',
    'specs/real-world/googleapis.com/cloudmonitoring/v2beta2/swagger.json',
    'specs/real-world/googleapis.com/cloudresourcemanager/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/clouduseraccounts/alpha/swagger.json',
    'specs/real-world/googleapis.com/clouduseraccounts/beta/swagger.json',
    'specs/real-world/googleapis.com/clouduseraccounts/vm_alpha/swagger.json',
    'specs/real-world/googleapis.com/clouduseraccounts/vm_beta/swagger.json',
    'specs/real-world/googleapis.com/compute/v1/swagger.json',
    'specs/real-world/googleapis.com/container/v1/swagger.json',
    'specs/real-world/googleapis.com/content/v2/swagger.json',
    'specs/real-world/googleapis.com/content/v2sandbox/swagger.json',
    'specs/real-world/googleapis.com/coordinate/v1/swagger.json',
    'specs/real-world/googleapis.com/customsearch/v1/swagger.json',
    'specs/real-world/googleapis.com/dataflow/v1b3/swagger.json',
    'specs/real-world/googleapis.com/datastore/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/datastore/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/deploymentmanager/v2/swagger.json',
    'specs/real-world/googleapis.com/deploymentmanager/v2beta1/swagger.json',
    'specs/real-world/googleapis.com/deploymentmanager/v2beta2/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v1/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v1.1/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v1.2/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v1.3/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v2.0/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v2.1/swagger.json',
    'specs/real-world/googleapis.com/dfareporting/v2.2/swagger.json',
    'specs/real-world/googleapis.com/discovery/v1/swagger.json',
    'specs/real-world/googleapis.com/dns/v1/swagger.json',
    'specs/real-world/googleapis.com/dns/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/doubleclickbidmanager/v1/swagger.json',
    'specs/real-world/googleapis.com/doubleclicksearch/v2/swagger.json',
    'specs/real-world/googleapis.com/drive/v1/swagger.json',
    'specs/real-world/googleapis.com/drive/v2/swagger.json',
    'specs/real-world/googleapis.com/fitness/v1/swagger.json',
    'specs/real-world/googleapis.com/freebase/v1/swagger.json',
    'specs/real-world/googleapis.com/fusiontables/v1/swagger.json',
    'specs/real-world/googleapis.com/fusiontables/v2/swagger.json',
    'specs/real-world/googleapis.com/games/v1/swagger.json',
    'specs/real-world/googleapis.com/gamesConfiguration/v1configuration/swagger.json',
    'specs/real-world/googleapis.com/gamesManagement/v1management/swagger.json',
    'specs/real-world/googleapis.com/gan/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/genomics/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/gmail/v1/swagger.json',
    'specs/real-world/googleapis.com/groupsmigration/v1/swagger.json',
    'specs/real-world/googleapis.com/groupssettings/v1/swagger.json',
    'specs/real-world/googleapis.com/identitytoolkit/v3/swagger.json',
    'specs/real-world/googleapis.com/licensing/v1/swagger.json',
    'specs/real-world/googleapis.com/logging/v1beta3/swagger.json',
    'specs/real-world/googleapis.com/manager/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/mirror/v1/swagger.json',
    'specs/real-world/googleapis.com/oauth2/v1/swagger.json',
    'specs/real-world/googleapis.com/oauth2/v2/swagger.json',
    'specs/real-world/googleapis.com/pagespeedonline/v1/swagger.json',
    'specs/real-world/googleapis.com/pagespeedonline/v2/swagger.json',
    'specs/real-world/googleapis.com/partners/v2/swagger.json',
    'specs/real-world/googleapis.com/playmoviespartner/v1/swagger.json',
    'specs/real-world/googleapis.com/plus/v1/swagger.json',
    'specs/real-world/googleapis.com/plusDomains/v1/swagger.json',
    'specs/real-world/googleapis.com/prediction/v1.2/swagger.json',
    'specs/real-world/googleapis.com/prediction/v1.3/swagger.json',
    'specs/real-world/googleapis.com/prediction/v1.4/swagger.json',
    'specs/real-world/googleapis.com/prediction/v1.5/swagger.json',
    'specs/real-world/googleapis.com/prediction/v1.6/swagger.json',
    'specs/real-world/googleapis.com/qpxExpress/v1/swagger.json',
    'specs/real-world/googleapis.com/replicapool/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/replicapool/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/replicapoolupdater/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/reseller/v1/swagger.json',
    'specs/real-world/googleapis.com/reseller/v1sandbox/swagger.json',
    'specs/real-world/googleapis.com/resourceviews/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/resourceviews/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/siteVerification/v1/swagger.json',
    'specs/real-world/googleapis.com/spectrum/v1explorer/swagger.json',
    'specs/real-world/googleapis.com/sqladmin/v1beta3/swagger.json',
    'specs/real-world/googleapis.com/sqladmin/v1beta4/swagger.json',
    'specs/real-world/googleapis.com/storage/v1/swagger.json',
    'specs/real-world/googleapis.com/storage/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/storage/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/tagmanager/v1/swagger.json',
    'specs/real-world/googleapis.com/taskqueue/v1beta1/swagger.json',
    'specs/real-world/googleapis.com/taskqueue/v1beta2/swagger.json',
    'specs/real-world/googleapis.com/tasks/v1/swagger.json',
    'specs/real-world/googleapis.com/translate/v2/swagger.json',
    'specs/real-world/googleapis.com/urlshortener/v1/swagger.json',
    'specs/real-world/googleapis.com/webfonts/v1/swagger.json',
    'specs/real-world/googleapis.com/webmasters/v3/swagger.json',
    'specs/real-world/googleapis.com/youtube/v3/swagger.json',
    'specs/real-world/googleapis.com/youtubeAnalytics/v1/swagger.json',
    'specs/real-world/googleapis.com/youtubeAnalytics/v1beta1/swagger.json',
    'specs/real-world/gsa.gov/0.1/swagger.json',
    'specs/real-world/hetras.net/1.0.0/swagger.json',
    'specs/real-world/iamreal.me/1.0.0/swagger.json',
    'specs/real-world/idtbeyond.com/1.0.0/swagger.json',
    'specs/real-world/infermedica.com/v1/swagger.json',
    'specs/real-world/instagram.com/1.0.0/swagger.json',
    'specs/real-world/likefolio.com/v0/swagger.json',
    'specs/real-world/loginbycall.com/v1/swagger.json',
    'specs/real-world/magick.nu/1.0/swagger.json',
    'specs/real-world/mondiamedia.com/2.9.10/swagger.json',
    'specs/real-world/moonmoonmoonmoon.com/1.0/swagger.json',
    'specs/real-world/neowsapp.com/1.0/swagger.json',
    'specs/real-world/nrel.gov/0.1.0/swagger.json',
    'specs/real-world/nsidc.org/1.0.0/swagger.json',
    'specs/real-world/oceandrivers.com/1.0/swagger.json',
    'specs/real-world/orghunter.com/1.0.0/swagger.json',
    'specs/real-world/owler.com/1.0.0/swagger.json',
    'specs/real-world/pandorabots.com/1.0.0/swagger.json',
    'specs/real-world/patientview.org/1.0/swagger.json',
    'specs/real-world/peel-ci.com/1.0.0/swagger.json',
    'specs/real-world/pollencheck.eu/1.0.0/swagger.json',
    'specs/real-world/posty-api.herokuapp.com/v1/swagger.json',
    'specs/real-world/prd-prsn.com/1.0.0/swagger.json',
    'specs/real-world/reactome.org/1.0/swagger.json',
    'specs/real-world/rummblelabs.com/1.0.0/swagger.json',
    'specs/real-world/scrapewebsite.email/0.1/swagger.json',
    'specs/real-world/slideroom.com/v2/swagger.json',
    'specs/real-world/solarvps.com/1.0.0/swagger.json',
    'specs/real-world/spectrocoin.com/1.0.0/swagger.json',
    'specs/real-world/storecheckerapi.com/0.1/swagger.json',
    'specs/real-world/taxamo.com/1/swagger.json',
    'specs/real-world/unavco.org/1.0.0/swagger.json',
    'specs/real-world/vatapi.com/1/swagger.json',
    'specs/real-world/waag.org/v1/swagger.json',
    'specs/real-world/yunbi.com/v2/swagger.json',
    'specs/real-world/zoomconnect.com/1/swagger.json'
  ];
}
