# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config-modular/

root: true

extends:
  - modular/best-practices
  - modular/style
  - modular/browser
  - modular/node
  - modular/es6

globals:
  Promise: false

rules:
  # This rule erroneously flags functions that use the `arguments` object
  no-unused-vars: off
