# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config-modular/

extends:
  - modular/node

env:
  jquery: true

globals:
  # Google Analytics
  gtag: false

  # ACE Editor
  ace: false
